# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Traverse < Formula
  desc "Build and maintain groups on the basis of reporting hierarchy."
  homepage "https://github.com/joefitzgerald/traverse"
  version "0.0.20"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mikfreedman/traverse/releases/download/v0.0.20/traverse_v0.0.20_darwin_arm64.tar.gz"
      sha256 "bf5b1c3fbff7b77ec954762644d2e213ceb6709ad6b9a12850c3485769bebfcf"

      def install
        bin.install "traverse"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mikfreedman/traverse/releases/download/v0.0.20/traverse_v0.0.20_darwin_x86_64.tar.gz"
      sha256 "de42ea9e02395618355d587c9c0383c2b4e71ac1076555788cffdd1b083c93c9"

      def install
        bin.install "traverse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mikfreedman/traverse/releases/download/v0.0.20/traverse_v0.0.20_linux_arm64.tar.gz"
      sha256 "28a4fa08ab7d9bdf75aa7bda799fe76f0f4b11a5f3583c9182ef9de367f0693a"

      def install
        bin.install "traverse"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mikfreedman/traverse/releases/download/v0.0.20/traverse_v0.0.20_linux_x86_64.tar.gz"
      sha256 "f9fee60409cf77f10f25a9ccb80d0a24d8aa8be189c80e4c12da7b1e006f3bef"

      def install
        bin.install "traverse"
      end
    end
  end

  test do
    system "#{bin}/traverse --version"
  end
end
