# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gabby < Formula
  desc "Gabby is a helpful assistant for your organization's directory and calendar systems, that currently supports Office 365."
  homepage "https://github.com/joefitzgerald/gabby"
  version "0.6.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joefitzgerald/gabby/releases/download/v0.6.2/gabby_v0.6.2_Darwin_x86_64.tar.gz"
      sha256 "031752072113a59bd02580c7177afb4a62fc3a7d5748a0c88d7c74b9856ab2e3"

      def install
        bin.install "gabby"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joefitzgerald/gabby/releases/download/v0.6.2/gabby_v0.6.2_Darwin_arm64.tar.gz"
      sha256 "684ffc8f744f5f1a1f778acec35c071a40812458f7f6d2421b0a49497e21efd8"

      def install
        bin.install "gabby"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joefitzgerald/gabby/releases/download/v0.6.2/gabby_v0.6.2_Linux_arm64.tar.gz"
      sha256 "fe9524caf2dd80a6f51a7cacce0dbf5dab3f3cb882938c2e3b49ec50f7467d49"

      def install
        bin.install "gabby"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joefitzgerald/gabby/releases/download/v0.6.2/gabby_v0.6.2_Linux_x86_64.tar.gz"
      sha256 "941dc5ef4e539df32513ee1f6d980bc9dab3046ec8912953f83dc6e40d7f5e55"

      def install
        bin.install "gabby"
      end
    end
  end

  test do
    system "#{bin}/gabby --version"
  end
end
