# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gabby < Formula
  desc "Gabby is a helpful assistant for your organization's directory and calendar systems, that currently supports Office 365."
  homepage "https://github.com/joefitzgerald/gabby"
  version "0.6.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joefitzgerald/gabby/releases/download/v0.6.1/gabby_v0.6.1_Darwin_x86_64.tar.gz"
      sha256 "3be535c040ed26589d4511f5e18644cd453c86a54efd0f1eae7dd959f85d8100"

      def install
        bin.install "gabby"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joefitzgerald/gabby/releases/download/v0.6.1/gabby_v0.6.1_Darwin_arm64.tar.gz"
      sha256 "3ac979daf4129190b099d5e6a4c8ea3138f276c5f123bae423ec1a5c2feb7de4"

      def install
        bin.install "gabby"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/joefitzgerald/gabby/releases/download/v0.6.1/gabby_v0.6.1_Linux_x86_64.tar.gz"
      sha256 "04402569fce53530211b0e9164251ed77593503dec94baa7b88443227a94542c"

      def install
        bin.install "gabby"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joefitzgerald/gabby/releases/download/v0.6.1/gabby_v0.6.1_Linux_arm64.tar.gz"
      sha256 "4cd2f15f9cc3b2f7691fb9eebcc3488accf8dd9d5121c5ac965da0bcf5c477d6"

      def install
        bin.install "gabby"
      end
    end
  end

  test do
    system "#{bin}/gabby --version"
  end
end
