# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Traverse < Formula
  desc "Build and maintain groups on the basis of reporting hierarchy."
  homepage "https://github.com/joefitzgerald/traverse"
  version "0.0.15"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joefitzgerald/traverse/releases/download/v0.0.15/traverse_v0.0.15_darwin_x86_64.tar.gz"
      sha256 "fd79e33c5f7fc05a65ab918c78fae89e1b9fa1ef3d8333214c9c7200d5aa09d1"

      def install
        bin.install "traverse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joefitzgerald/traverse/releases/download/v0.0.15/traverse_v0.0.15_darwin_arm64.tar.gz"
      sha256 "60493847d9ff64402369b826769525dcfa2cc3b6da7c0dcdb123b6ee394b9dd8"

      def install
        bin.install "traverse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joefitzgerald/traverse/releases/download/v0.0.15/traverse_v0.0.15_linux_arm64.tar.gz"
      sha256 "aa4b32a71ed90feda15e3c3e09099f2c378509520ad44c0277b25915591796c8"

      def install
        bin.install "traverse"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joefitzgerald/traverse/releases/download/v0.0.15/traverse_v0.0.15_linux_x86_64.tar.gz"
      sha256 "456d3e058b88d7ab195d1eb88daf2aac0624523bc5d44e2524d4c4681eaf8964"

      def install
        bin.install "traverse"
      end
    end
  end

  test do
    system "#{bin}/traverse --version"
  end
end
